### ISSUE TITLE
New ESModule script.

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [nothingrandom/leadingzero#3]
It would be great if you wrote it in the new ESModule import and exports, and then compiled it to CommonJS to support CommonJS.

Can I please make a pull request switching to ESModules? The functionality will still be the same, and it can you rollup to compile it to commonjs.

Also, this is the best npm package I found for leading zeros, because some other ones had the number of zeros as the first parameter and the actual number as the second parameter. I like this one because the actual number comes first.

**Comment by nothingrandom** [comment]
Hi, thanks for your interest in this project!
I'm not especially interested in making the conversion to ESModules myself right now, but you are very welcome to open a pull request with your suggestion.

**Comment by ChocolateLoverRaj** [comment]
Ok, I will make a pull request with ESModules. It won't be that complicated because its just `index.js`. Should I include the compiled CommonJS module in github, or have it in a post install script so that users will be able to use it after installing it without it having to be in github?
